### ISSUE TITLE
Level Editor: After the public beta patch on 28/06/2023 some objects are randomly not selectable.

### ISSUE THREAD

**Issue by GyalayPaul** [jkulawik/bunker-issues#21] opened 2023-06-29 17:04 UTC
Some objects are randmly very hard or impossible to select in the editor after the update. This is one of the examples: 
![image](https://github.com/jkulawik/bunker-issues/assets/12644719/d201d5fe-587b-4ea6-8f60-61078528a30b)
You can test this out by sleecting big chunks of the map and deleting them, some objects will remain with very unreliable ways to select them. This was tested and compared with the current default build compared to the public beta one on 29/06/2023. 

![image](https://github.com/jkulawik/bunker-issues/assets/12644719/42eab316-44ab-48e0-a2c9-5132ddfee6d5)
![image](https://github.com/jkulawik/bunker-issues/assets/12644719/51a78a1f-ecda-4fbf-a018-9c6d4fad7481)

**Comment by GyalayPaul** [comment] 2023-07-07 17:18
Also worth nothing that those objects tend to have some strange culling behaviour if viewed from wireframe mode.

**Comment by jkulawik** [comment] 2024-05-29 18:22
I can't reproduce this - whole map selects correctly (I deleted it all). Might be fixed now

**Comment by AndrewIsGreen** [comment] 2024-05-31 04:59
Remembered having this issue constantly a while back, on multiple maps. Here's a video comparing my old backup files, and a fresh install. Seems fixed

https://github.com/jkulawik/bunker-issues/assets/13738394/d5efd4c3-229e-4ca7-8cd9-38b24b919385

**Comment by jkulawik** [comment] 2024-05-31 11:17
Nice, thanks

**Closed by jkulawik** 2024-05-31 11:17 UTC
Labels: topic:editors, severity:high, retest needed, v1.1
